- flake.nix
Closes https://github.com/orhun/binsider/issues/27
Please check my comment on issue for more info
> fix(flake): fix test failure on Nix

- src/file.rs
Fixes #21
Not tested, but it's a simple change.
> fix(file): do not panic if creation time is not supported

- src/app.rs
- src/tui/state.rs
Now we sort the list of shared libraries.
If the library starts with `lib` it takes precedence.
Locally.
> fix(dynamic): sort the shared library list

- src/file.rs
- src/lib.rs
- src/tracer.rs
This PR makes it possible to run binaries with specified arguments. e.g.
```bash
binsider "python test.py"
```
https://github.com/orhun/binsider/issues/7#issuecomment-2366809180
Locally
> feat(dynamic): support running binaries with CLI arguments

- Cargo.lock
- Cargo.toml
fixes #43
depends on https://github.com/JakWai01/lurk/pull/52
Locally.
> fix(dynamic): fix locating the binary

- src/tui/ui.rs
This change adds support for showing the number of shared libraries when the app starts with a binary. The same logic as used in other such lists is used. Closes #54.
Ran the binary with different files to verify that the number of shared libraries shown is correct.
> feat(general): display the number of shared libraries

- src/args.rs
- src/lib.rs
- src/tui/state.rs
- src/tui/ui.rs
This feature lets user launch binsider from a different tab other than general
closes #6 
running `binsider` should start at general tab, the default value 
if you run 
```shell
binsider --tab hexdump
```
binsider should be running at hexdump tab
also if you mistype you get this message 
```shell
❯ binsider --tab hex
error: invalid value 'hex' for '--tab <TAB>'
[possible values: general, static-analysis, dynamic-analysis, strings, hexdump]
tip: a similar value exists: 'hexdump'
For more information, try '--help'.
```
> feat(cli): add `--tab` argument

- flake.lock
- flake.nix
This adds meta section which is needed for example to show description of a package
> fix(flake): add missing meta section to flake

- .github/workflows/ci.yml
- flake.nix
> chore(ci): add nix flake build

- flake.lock
- flake.nix
Build using [naersk](https://github.com/nix-community/naersk) which is much faster on rebuilds
When building using https://github.com/orhun/binsider/pull/75 time decreases from 3m2s to 1m40s
(https://github.com/ch4og/binsider/actions/runs/11246715759/job/31268990666)
> perf(flake): speed up rebuild by using naersk

- examples/demo.rs
- src/args.rs
- src/lib.rs
- src/main.rs
- src/tui/state.rs
- website/src/content/docs/extras/library.md
fixes #59
Also adds a new CLI argument for overriding the accent color.
Locally.
> fix(tui)!: query the terminal background once

- src/lib.rs
- src/tui/mod.rs
Use stdout instead of stderr, see <https://blog.orhun.dev/stdout-vs-stderr/>
Locally.
> feat(tui): use stdout for rendering

- src/elf/header.rs
- src/elf/mod.rs
- src/tui/command.rs
- src/tui/state.rs
Added KeyCommand HumanReadable that toggles the format for FileSiz and MemSiz in Tab::StaticAnalysis => Program Headers. Keybind is 's'
Closes Issue #47
Verified the program to correctly toggle human readable on and off only on tab StaticAnalysis.
> feat(static): add human readable option for program headers

- src/tui/state.rs
See https://github.com/orhun/binsider/pull/77#discussion_r1796114961
Locally.
> fix(dynamic): only allow tracing calls while on the dynamic analysis tab

- .github/workflows/ci.yml
Now it will add `Cargo.toml`, `Cargo.lock`, `flake.lock` hashes to cache name so if dependency updates in these files it will know that new cache should be saved.
Also since much more caches will be created cause of this it adds auto purge of old unused caches (only Nix ones) 
It won't affect build time since when dependency version changes it'll use old partial cache
> chore(ci): track dependencies updates to add them to Nix cache

- .github/workflows/flake-update.yml
- flake.nix
Automatically creates PR with `flake.lock` update, which is file with Nix dependencies
It doesn't run it on PRs not to create PRs from PRs
Here is action run https://github.com/thingsbych/binsider/actions/runs/11388924732/job/31687028064
And PR that it created https://github.com/thingsbych/binsider/pull/3
> chore(github): create PRs for nix flake updates automatically

- website/src/content/docs/architecture.md
As discussed on discord, I've created Architecture document.
The markdown file contains the mermaid diagram code.
Benefit of this (over uploading an image) is that we do not need to keep updating the image.
Instead the mermaid diagram code itself can be updated (suing any editor) and changes will be reflected in the rendered image.
I verified that the image is correctly rendered using github's built-in editor (`preview` tab)
> docs(architecture): add architecture diagram

- src/elf/header.rs
- src/tui/state.rs
Readability feature now works for Static Tab / Section headers /Size as well.
Verified the program to correctly toggle human readable on and off only on tab StaticAnalysis.
> feat(static): add human readable option for Static/Section headers/ Size

- Cargo.lock
- Cargo.toml
- examples/demo.rs
- src/elf/dynamic.rs
- src/elf/header.rs
- src/elf/relocations.rs
- src/elf/symbols.rs
Run cargo clippy and follow suggestions + fmt
> Fix CI with clippy fixes, update some dependencies

- src/tui/command.rs
- src/tui/state.rs
The effect of the change was manually tested.
> fix(ui): don't exit when typing 'q' in hexdump search and jump
